@startuml 
skinparam monochrome true
skinparam backgroundColor #EEEEEE
hide empty description
title Project state description\n


[*] --> Initialisation : Regular boot
[*] --> Initialisation : File input boot
Initialisation --> Reverse_Graph_DFS
Reverse_Graph_DFS --> Reverse_Graph_DFS : steps
Reverse_Graph_DFS --> Prioritised_Graph_DFS : nodes order is completed 
Prioritised_Graph_DFS --> Prioritised_Graph_DFS : steps 
Prioritised_Graph_DFS --> Completed : no unhandeled nodes left
Completed --> Initialisation : new data or other actions
Initialisation --> [*] : close app

@enduml